### ISSUE TITLE
Heap

### ISSUE THREAD

**Issue by KevinAlavik** [KevinAlavik/Paradox#17]

**Comment by KevinAlavik** [comment]
Ill quikly add malloc, realloc, free and that later.

**Comment by lolguy91** [comment]
heap more like heap of bullshit

you can just use ur pmm for heap lol

**Comment by KevinAlavik** [comment]
@lolguy91 yep i will! pmm heap

**Comment by KevinAlavik** [comment]
![image](https://github.com/KevinAlavik/Paradox/assets/95900603/5f3dba98-eabd-4aed-9fcc-6d3cdeb09876)
done!
